from app.application import create_app


def test_create_app_registers_core_routes():
    app = create_app()
    paths = {route.path for route in app.routes}

    assert "/health" in paths
    assert "/api/auth/login" in paths
    assert "/api/auth/avatar" in paths
    assert "/api/auth/change-username" in paths
    assert "/api/auth/signature" in paths
    assert "/api/users/{username}/profile" in paths
    assert "/api/users/{user_id}/avatar" in paths
    assert "/api/problems/{slug}/resources" in paths
    assert "/api/problems/{slug}/resource-files/{asset_path:path}" in paths
    assert "/api/problems/{slug}/statement-pdfs/{asset_id}" in paths
    assert "/api/submissions/{submission_id}/cancel" in paths
    assert "/api/submissions/{submission_id}/source" in paths
    assert "/api/admin/problems/import" in paths
    assert "/api/admin/analytics/overview" in paths
    assert "/api/admin/problems/{slug}/editor" in paths
    assert "/api/admin/problems/{slug}/draft" in paths
    assert "/api/admin/problems/{slug}/meta" in paths
    assert "/api/admin/problems/{slug}/versions/{version_id}/statement-markdowns/{asset_id}" in paths
    assert "/api/admin/problems/{slug}/versions/{version_id}/statement-pdfs" in paths
    assert "/api/admin/problems/{slug}/versions/{version_id}/statement-assets/{kind}/{asset_id}" in paths
    assert "/api/admin/audit-logs" in paths
    assert "/api/admin/problems/{slug}/versions" in paths
    assert "/api/admin/judge/overview" in paths
    assert "/api/internal/judge/claim" in paths
    assert "/api/internal/judge/heartbeat" in paths
    assert "/api/contests/{slug}/scoreboard-advanced" in paths
    assert "/api/notifications" in paths
    assert "/api/admin/notifications/broadcast" in paths
    assert "/api/drive/summary" in paths
    assert "/api/drive/items" in paths
    assert "/api/drive/folders" in paths
    assert "/api/drive/files" in paths
    assert "/api/drive/search" in paths
    assert "/api/drive/batch/move" in paths
    assert "/api/drive/batch/delete" in paths
    assert "/api/drive/batch/download" in paths
    assert "/api/drive/items/{item_id}" in paths
    assert "/api/drive/items/{item_id}/preview" in paths
    assert "/api/drive/items/{item_id}/shares" in paths
    assert "/api/drive/items/{item_id}/download" in paths
    assert "/api/drive/shares/{share_id}" in paths
    assert "/api/drive/shares/{token}" in paths
    assert "/api/drive/shares/{token}/preview" in paths
    assert "/api/drive/shares/{token}/download" in paths
    assert "/api/messages/conversations" in paths
    assert "/api/messages/unread-count" in paths
    assert "/api/messages/events" in paths
    assert "/api/messages/presence/heartbeat" in paths
    assert "/api/messages/preferences" in paths
    assert "/api/messages/typing" in paths
    assert "/api/messages/search" in paths
    assert "/api/messages/files" in paths
    assert "/api/messages/images" in paths
    assert "/api/messages/groups" in paths
    assert "/api/messages/groups/{group_id}" in paths
    assert "/api/messages/groups/{group_id}/members" in paths
    assert "/api/messages/groups/{group_id}/announcements" in paths
    assert "/api/messages/groups/{group_id}/invites" in paths
    assert "/api/messages/group-invites/join" in paths
    assert "/api/messages/groups/{group_id}/messages" in paths
    assert "/api/messages/groups/{group_id}/files" in paths
    assert "/api/messages/groups/{group_id}/read" in paths
    assert "/api/messages/groups/{group_id}/leave" in paths
    assert "/api/messages/groups/{group_id}/transfer-owner" in paths
    assert "/api/messages/groups/{group_id}/members/{member_id}" in paths
    assert "/api/messages/groups/{group_id}/members/{member_id}/role" in paths
    assert "/api/messages/groups/{group_id}/members/{member_id}/remove" in paths
    assert "/api/messages/conversation-preferences/{conversation_type}/{conversation_id}" in paths
    assert "/api/messages/blocks" in paths
    assert "/api/messages/blocks/{blocked_user_id}" in paths
    assert "/api/messages/reports" in paths
    assert "/api/admin/messages/reports" in paths
    assert "/api/admin/messages/reports/{report_id}" in paths
    assert "/api/messages/reactions" in paths
    assert "/api/messages/favorites" in paths
    assert "/api/messages/favorites/{conversation_type}/{message_id}" in paths
    assert "/api/messages/direct-messages/{message_id}" in paths
    assert "/api/messages/direct-messages/{message_id}/recall" in paths
    assert "/api/messages/group-messages/{message_id}" in paths
    assert "/api/messages/group-messages/{message_id}/recall" in paths
    assert "/api/messages/group-messages/{message_id}/reads" in paths
    assert "/api/messages/group-messages/{message_id}/attachment" in paths
    assert "/api/messages/{message_id}/attachment" in paths
    assert "/api/messages/{message_id}/image" in paths
